// megafunction wizard: %RAM: 1-PORT%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: altsyncram 

// ============================================================
// File Name: DataMemory.v
// Megafunction Name(s):
// 			altsyncram
//
// Simulation Library Files(s):
// 			altera_mf
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 20.1.1 Build 720 11/11/2020 SJ Lite Edition
// ************************************************************


//Copyright (C) 2020  Intel Corporation. All rights reserved.
//Your use of Intel Corporation's design tools, logic functions 
//and other software and tools, and any partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Intel Program License 
//Subscription Agreement, the Intel Quartus Prime License Agreement,
//the Intel FPGA IP License Agreement, or other applicable license
//agreement, including, without limitation, that your use is for
//the sole purpose of programming logic devices manufactured by
//Intel and sold by Intel or its authorized distributors.  Please
//refer to the applicable agreement for further details, at
//https://fpgasoftware.intel.com/eula.


//altsyncram CLOCK_ENABLE_INPUT_A="BYPASS" CLOCK_ENABLE_OUTPUT_A="BYPASS" DEVICE_FAMILY="Cyclone IV E" ENABLE_RUNTIME_MOD="YES" INIT_FILE="D.mif" INSTANCE_NAME="DATA" NUMWORDS_A=256 OPERATION_MODE="SINGLE_PORT" OUTDATA_ACLR_A="NONE" OUTDATA_REG_A="UNREGISTERED" POWER_UP_UNINITIALIZED="FALSE" read_during_write_mode_port_a="OLD_DATA" WIDTH_A=16 WIDTH_BYTEENA_A=1 WIDTHAD_A=8 address_a clock0 data_a q_a wren_a
//VERSION_BEGIN 20.1 cbx_altera_syncram_nd_impl 2020:11:11:17:06:45:SJ cbx_altsyncram 2020:11:11:17:06:45:SJ cbx_cycloneii 2020:11:11:17:06:45:SJ cbx_lpm_add_sub 2020:11:11:17:06:45:SJ cbx_lpm_compare 2020:11:11:17:06:45:SJ cbx_lpm_decode 2020:11:11:17:06:45:SJ cbx_lpm_mux 2020:11:11:17:06:45:SJ cbx_mgl 2020:11:11:17:08:38:SJ cbx_nadder 2020:11:11:17:06:46:SJ cbx_stratix 2020:11:11:17:06:46:SJ cbx_stratixii 2020:11:11:17:06:46:SJ cbx_stratixiii 2020:11:11:17:06:46:SJ cbx_stratixv 2020:11:11:17:06:46:SJ cbx_util_mgl 2020:11:11:17:06:46:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463



//altsyncram ADDRESS_ACLR_B="NONE" ADDRESS_REG_B="CLOCK1" CLOCK_ENABLE_INPUT_A="BYPASS" CLOCK_ENABLE_OUTPUT_A="BYPASS" DEVICE_FAMILY="Cyclone IV E" ENABLE_RUNTIME_MOD="NO" INDATA_ACLR_B="NONE" INDATA_REG_B="CLOCK1" INIT_FILE="D.mif" NUMWORDS_A=256 NUMWORDS_B=256 OPERATION_MODE="BIDIR_DUAL_PORT" OUTDATA_ACLR_A="NONE" OUTDATA_ACLR_B="NONE" OUTDATA_REG_A="UNREGISTERED" OUTDATA_REG_B="UNREGISTERED" RDCONTROL_REG_B="CLOCK1" read_during_write_mode_port_a="OLD_DATA" WIDTH_A=16 WIDTH_B=16 WIDTH_BYTEENA_A=1 WIDTHAD_A=8 WIDTHAD_B=8 WRCONTROL_ACLR_B="NONE" WRCONTROL_WRADDRESS_REG_B="CLOCK1" address_a address_b clock0 clock1 data_a data_b q_a q_b wren_a wren_b
//VERSION_BEGIN 20.1 cbx_altera_syncram_nd_impl 2020:11:11:17:06:45:SJ cbx_altsyncram 2020:11:11:17:06:45:SJ cbx_cycloneii 2020:11:11:17:06:45:SJ cbx_lpm_add_sub 2020:11:11:17:06:45:SJ cbx_lpm_compare 2020:11:11:17:06:45:SJ cbx_lpm_decode 2020:11:11:17:06:45:SJ cbx_lpm_mux 2020:11:11:17:06:45:SJ cbx_mgl 2020:11:11:17:08:38:SJ cbx_nadder 2020:11:11:17:06:46:SJ cbx_stratix 2020:11:11:17:06:46:SJ cbx_stratixii 2020:11:11:17:06:46:SJ cbx_stratixiii 2020:11:11:17:06:46:SJ cbx_stratixv 2020:11:11:17:06:46:SJ cbx_util_mgl 2020:11:11:17:06:46:SJ  VERSION_END

//synthesis_resources = M9K 1 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"OPTIMIZE_POWER_DURING_SYNTHESIS=NORMAL_COMPILATION"} *)
module  DataMemory_altsyncram1
	( 
	address_a,
	address_b,
	clock0,
	clock1,
	data_a,
	data_b,
	q_a,
	q_b,
	wren_a,
	wren_b) /* synthesis synthesis_clearbox=1 */;
	input   [7:0]  address_a;
	input   [7:0]  address_b;
	input   clock0;
	input   clock1;
	input   [15:0]  data_a;
	input   [15:0]  data_b;
	output   [15:0]  q_a;
	output   [15:0]  q_b;
	input   wren_a;
	input   wren_b;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1   [7:0]  address_b;
	tri1   clock0;
	tri1   clock1;
	tri1   [15:0]  data_a;
	tri1   [15:0]  data_b;
	tri0   wren_a;
	tri0   wren_b;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [0:0]   wire_ram_block3a_0portadataout;
	wire  [0:0]   wire_ram_block3a_1portadataout;
	wire  [0:0]   wire_ram_block3a_2portadataout;
	wire  [0:0]   wire_ram_block3a_3portadataout;
	wire  [0:0]   wire_ram_block3a_4portadataout;
	wire  [0:0]   wire_ram_block3a_5portadataout;
	wire  [0:0]   wire_ram_block3a_6portadataout;
	wire  [0:0]   wire_ram_block3a_7portadataout;
	wire  [0:0]   wire_ram_block3a_8portadataout;
	wire  [0:0]   wire_ram_block3a_9portadataout;
	wire  [0:0]   wire_ram_block3a_10portadataout;
	wire  [0:0]   wire_ram_block3a_11portadataout;
	wire  [0:0]   wire_ram_block3a_12portadataout;
	wire  [0:0]   wire_ram_block3a_13portadataout;
	wire  [0:0]   wire_ram_block3a_14portadataout;
	wire  [0:0]   wire_ram_block3a_15portadataout;
	wire  [0:0]   wire_ram_block3a_0portbdataout;
	wire  [0:0]   wire_ram_block3a_1portbdataout;
	wire  [0:0]   wire_ram_block3a_2portbdataout;
	wire  [0:0]   wire_ram_block3a_3portbdataout;
	wire  [0:0]   wire_ram_block3a_4portbdataout;
	wire  [0:0]   wire_ram_block3a_5portbdataout;
	wire  [0:0]   wire_ram_block3a_6portbdataout;
	wire  [0:0]   wire_ram_block3a_7portbdataout;
	wire  [0:0]   wire_ram_block3a_8portbdataout;
	wire  [0:0]   wire_ram_block3a_9portbdataout;
	wire  [0:0]   wire_ram_block3a_10portbdataout;
	wire  [0:0]   wire_ram_block3a_11portbdataout;
	wire  [0:0]   wire_ram_block3a_12portbdataout;
	wire  [0:0]   wire_ram_block3a_13portbdataout;
	wire  [0:0]   wire_ram_block3a_14portbdataout;
	wire  [0:0]   wire_ram_block3a_15portbdataout;
	wire  [7:0]  address_a_wire;
	wire  [7:0]  address_b_wire;

	cycloneive_ram_block   ram_block3a_0
	( 
	.clk0(clock0),
	.clk1(clock1),
	.portaaddr({address_a_wire[7:0]}),
	.portadatain({data_a[0]}),
	.portadataout(wire_ram_block3a_0portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdatain({data_b[0]}),
	.portbdataout(wire_ram_block3a_0portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_0.clk0_core_clock_enable = "none",
		ram_block3a_0.clk0_input_clock_enable = "none",
		ram_block3a_0.clk1_core_clock_enable = "none",
		ram_block3a_0.clk1_input_clock_enable = "none",
		ram_block3a_0.connectivity_checking = "OFF",
		ram_block3a_0.init_file = "D.mif",
		ram_block3a_0.init_file_layout = "port_a",
		ram_block3a_0.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_0.mem_init0 = 256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC0000000000000000FFFF8000001DB8D,
		ram_block3a_0.mixed_port_feed_through_mode = "dont_care",
		ram_block3a_0.operation_mode = "bidir_dual_port",
		ram_block3a_0.port_a_address_width = 8,
		ram_block3a_0.port_a_data_out_clear = "none",
		ram_block3a_0.port_a_data_width = 1,
		ram_block3a_0.port_a_first_address = 0,
		ram_block3a_0.port_a_first_bit_number = 0,
		ram_block3a_0.port_a_last_address = 255,
		ram_block3a_0.port_a_logical_ram_depth = 256,
		ram_block3a_0.port_a_logical_ram_width = 16,
		ram_block3a_0.port_a_read_during_write_mode = "old_data",
		ram_block3a_0.port_b_address_clock = "clock1",
		ram_block3a_0.port_b_address_width = 8,
		ram_block3a_0.port_b_data_in_clock = "clock1",
		ram_block3a_0.port_b_data_out_clear = "none",
		ram_block3a_0.port_b_data_width = 1,
		ram_block3a_0.port_b_first_address = 0,
		ram_block3a_0.port_b_first_bit_number = 0,
		ram_block3a_0.port_b_last_address = 255,
		ram_block3a_0.port_b_logical_ram_depth = 256,
		ram_block3a_0.port_b_logical_ram_width = 16,
		ram_block3a_0.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block3a_0.port_b_read_enable_clock = "clock1",
		ram_block3a_0.port_b_write_enable_clock = "clock1",
		ram_block3a_0.ram_block_type = "AUTO",
		ram_block3a_0.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block3a_1
	( 
	.clk0(clock0),
	.clk1(clock1),
	.portaaddr({address_a_wire[7:0]}),
	.portadatain({data_a[1]}),
	.portadataout(wire_ram_block3a_1portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdatain({data_b[1]}),
	.portbdataout(wire_ram_block3a_1portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_1.clk0_core_clock_enable = "none",
		ram_block3a_1.clk0_input_clock_enable = "none",
		ram_block3a_1.clk1_core_clock_enable = "none",
		ram_block3a_1.clk1_input_clock_enable = "none",
		ram_block3a_1.connectivity_checking = "OFF",
		ram_block3a_1.init_file = "D.mif",
		ram_block3a_1.init_file_layout = "port_a",
		ram_block3a_1.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_1.mem_init0 = 256'h0000000000000000000000000000000040000000000000000FFFFFFFF80199E5,
		ram_block3a_1.mixed_port_feed_through_mode = "dont_care",
		ram_block3a_1.operation_mode = "bidir_dual_port",
		ram_block3a_1.port_a_address_width = 8,
		ram_block3a_1.port_a_data_out_clear = "none",
		ram_block3a_1.port_a_data_width = 1,
		ram_block3a_1.port_a_first_address = 0,
		ram_block3a_1.port_a_first_bit_number = 1,
		ram_block3a_1.port_a_last_address = 255,
		ram_block3a_1.port_a_logical_ram_depth = 256,
		ram_block3a_1.port_a_logical_ram_width = 16,
		ram_block3a_1.port_a_read_during_write_mode = "old_data",
		ram_block3a_1.port_b_address_clock = "clock1",
		ram_block3a_1.port_b_address_width = 8,
		ram_block3a_1.port_b_data_in_clock = "clock1",
		ram_block3a_1.port_b_data_out_clear = "none",
		ram_block3a_1.port_b_data_width = 1,
		ram_block3a_1.port_b_first_address = 0,
		ram_block3a_1.port_b_first_bit_number = 1,
		ram_block3a_1.port_b_last_address = 255,
		ram_block3a_1.port_b_logical_ram_depth = 256,
		ram_block3a_1.port_b_logical_ram_width = 16,
		ram_block3a_1.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block3a_1.port_b_read_enable_clock = "clock1",
		ram_block3a_1.port_b_write_enable_clock = "clock1",
		ram_block3a_1.ram_block_type = "AUTO",
		ram_block3a_1.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block3a_2
	( 
	.clk0(clock0),
	.clk1(clock1),
	.portaaddr({address_a_wire[7:0]}),
	.portadatain({data_a[2]}),
	.portadataout(wire_ram_block3a_2portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdatain({data_b[2]}),
	.portbdataout(wire_ram_block3a_2portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_2.clk0_core_clock_enable = "none",
		ram_block3a_2.clk0_input_clock_enable = "none",
		ram_block3a_2.clk1_core_clock_enable = "none",
		ram_block3a_2.clk1_input_clock_enable = "none",
		ram_block3a_2.connectivity_checking = "OFF",
		ram_block3a_2.init_file = "D.mif",
		ram_block3a_2.init_file_layout = "port_a",
		ram_block3a_2.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_2.mem_init0 = 256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000040000019A6F,
		ram_block3a_2.mixed_port_feed_through_mode = "dont_care",
		ram_block3a_2.operation_mode = "bidir_dual_port",
		ram_block3a_2.port_a_address_width = 8,
		ram_block3a_2.port_a_data_out_clear = "none",
		ram_block3a_2.port_a_data_width = 1,
		ram_block3a_2.port_a_first_address = 0,
		ram_block3a_2.port_a_first_bit_number = 2,
		ram_block3a_2.port_a_last_address = 255,
		ram_block3a_2.port_a_logical_ram_depth = 256,
		ram_block3a_2.port_a_logical_ram_width = 16,
		ram_block3a_2.port_a_read_during_write_mode = "old_data",
		ram_block3a_2.port_b_address_clock = "clock1",
		ram_block3a_2.port_b_address_width = 8,
		ram_block3a_2.port_b_data_in_clock = "clock1",
		ram_block3a_2.port_b_data_out_clear = "none",
		ram_block3a_2.port_b_data_width = 1,
		ram_block3a_2.port_b_first_address = 0,
		ram_block3a_2.port_b_first_bit_number = 2,
		ram_block3a_2.port_b_last_address = 255,
		ram_block3a_2.port_b_logical_ram_depth = 256,
		ram_block3a_2.port_b_logical_ram_width = 16,
		ram_block3a_2.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block3a_2.port_b_read_enable_clock = "clock1",
		ram_block3a_2.port_b_write_enable_clock = "clock1",
		ram_block3a_2.ram_block_type = "AUTO",
		ram_block3a_2.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block3a_3
	( 
	.clk0(clock0),
	.clk1(clock1),
	.portaaddr({address_a_wire[7:0]}),
	.portadatain({data_a[3]}),
	.portadataout(wire_ram_block3a_3portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdatain({data_b[3]}),
	.portbdataout(wire_ram_block3a_3portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_3.clk0_core_clock_enable = "none",
		ram_block3a_3.clk0_input_clock_enable = "none",
		ram_block3a_3.clk1_core_clock_enable = "none",
		ram_block3a_3.clk1_input_clock_enable = "none",
		ram_block3a_3.connectivity_checking = "OFF",
		ram_block3a_3.init_file = "D.mif",
		ram_block3a_3.init_file_layout = "port_a",
		ram_block3a_3.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_3.mem_init0 = 256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF80194B3,
		ram_block3a_3.mixed_port_feed_through_mode = "dont_care",
		ram_block3a_3.operation_mode = "bidir_dual_port",
		ram_block3a_3.port_a_address_width = 8,
		ram_block3a_3.port_a_data_out_clear = "none",
		ram_block3a_3.port_a_data_width = 1,
		ram_block3a_3.port_a_first_address = 0,
		ram_block3a_3.port_a_first_bit_number = 3,
		ram_block3a_3.port_a_last_address = 255,
		ram_block3a_3.port_a_logical_ram_depth = 256,
		ram_block3a_3.port_a_logical_ram_width = 16,
		ram_block3a_3.port_a_read_during_write_mode = "old_data",
		ram_block3a_3.port_b_address_clock = "clock1",
		ram_block3a_3.port_b_address_width = 8,
		ram_block3a_3.port_b_data_in_clock = "clock1",
		ram_block3a_3.port_b_data_out_clear = "none",
		ram_block3a_3.port_b_data_width = 1,
		ram_block3a_3.port_b_first_address = 0,
		ram_block3a_3.port_b_first_bit_number = 3,
		ram_block3a_3.port_b_last_address = 255,
		ram_block3a_3.port_b_logical_ram_depth = 256,
		ram_block3a_3.port_b_logical_ram_width = 16,
		ram_block3a_3.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block3a_3.port_b_read_enable_clock = "clock1",
		ram_block3a_3.port_b_write_enable_clock = "clock1",
		ram_block3a_3.ram_block_type = "AUTO",
		ram_block3a_3.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block3a_4
	( 
	.clk0(clock0),
	.clk1(clock1),
	.portaaddr({address_a_wire[7:0]}),
	.portadatain({data_a[4]}),
	.portadataout(wire_ram_block3a_4portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdatain({data_b[4]}),
	.portbdataout(wire_ram_block3a_4portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_4.clk0_core_clock_enable = "none",
		ram_block3a_4.clk0_input_clock_enable = "none",
		ram_block3a_4.clk1_core_clock_enable = "none",
		ram_block3a_4.clk1_input_clock_enable = "none",
		ram_block3a_4.connectivity_checking = "OFF",
		ram_block3a_4.init_file = "D.mif",
		ram_block3a_4.init_file_layout = "port_a",
		ram_block3a_4.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_4.mem_init0 = 256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFBFFFFFF8020,
		ram_block3a_4.mixed_port_feed_through_mode = "dont_care",
		ram_block3a_4.operation_mode = "bidir_dual_port",
		ram_block3a_4.port_a_address_width = 8,
		ram_block3a_4.port_a_data_out_clear = "none",
		ram_block3a_4.port_a_data_width = 1,
		ram_block3a_4.port_a_first_address = 0,
		ram_block3a_4.port_a_first_bit_number = 4,
		ram_block3a_4.port_a_last_address = 255,
		ram_block3a_4.port_a_logical_ram_depth = 256,
		ram_block3a_4.port_a_logical_ram_width = 16,
		ram_block3a_4.port_a_read_during_write_mode = "old_data",
		ram_block3a_4.port_b_address_clock = "clock1",
		ram_block3a_4.port_b_address_width = 8,
		ram_block3a_4.port_b_data_in_clock = "clock1",
		ram_block3a_4.port_b_data_out_clear = "none",
		ram_block3a_4.port_b_data_width = 1,
		ram_block3a_4.port_b_first_address = 0,
		ram_block3a_4.port_b_first_bit_number = 4,
		ram_block3a_4.port_b_last_address = 255,
		ram_block3a_4.port_b_logical_ram_depth = 256,
		ram_block3a_4.port_b_logical_ram_width = 16,
		ram_block3a_4.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block3a_4.port_b_read_enable_clock = "clock1",
		ram_block3a_4.port_b_write_enable_clock = "clock1",
		ram_block3a_4.ram_block_type = "AUTO",
		ram_block3a_4.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block3a_5
	( 
	.clk0(clock0),
	.clk1(clock1),
	.portaaddr({address_a_wire[7:0]}),
	.portadatain({data_a[5]}),
	.portadataout(wire_ram_block3a_5portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdatain({data_b[5]}),
	.portbdataout(wire_ram_block3a_5portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_5.clk0_core_clock_enable = "none",
		ram_block3a_5.clk0_input_clock_enable = "none",
		ram_block3a_5.clk1_core_clock_enable = "none",
		ram_block3a_5.clk1_input_clock_enable = "none",
		ram_block3a_5.connectivity_checking = "OFF",
		ram_block3a_5.init_file = "D.mif",
		ram_block3a_5.init_file_layout = "port_a",
		ram_block3a_5.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_5.mem_init0 = 256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFF0000,
		ram_block3a_5.mixed_port_feed_through_mode = "dont_care",
		ram_block3a_5.operation_mode = "bidir_dual_port",
		ram_block3a_5.port_a_address_width = 8,
		ram_block3a_5.port_a_data_out_clear = "none",
		ram_block3a_5.port_a_data_width = 1,
		ram_block3a_5.port_a_first_address = 0,
		ram_block3a_5.port_a_first_bit_number = 5,
		ram_block3a_5.port_a_last_address = 255,
		ram_block3a_5.port_a_logical_ram_depth = 256,
		ram_block3a_5.port_a_logical_ram_width = 16,
		ram_block3a_5.port_a_read_during_write_mode = "old_data",
		ram_block3a_5.port_b_address_clock = "clock1",
		ram_block3a_5.port_b_address_width = 8,
		ram_block3a_5.port_b_data_in_clock = "clock1",
		ram_block3a_5.port_b_data_out_clear = "none",
		ram_block3a_5.port_b_data_width = 1,
		ram_block3a_5.port_b_first_address = 0,
		ram_block3a_5.port_b_first_bit_number = 5,
		ram_block3a_5.port_b_last_address = 255,
		ram_block3a_5.port_b_logical_ram_depth = 256,
		ram_block3a_5.port_b_logical_ram_width = 16,
		ram_block3a_5.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block3a_5.port_b_read_enable_clock = "clock1",
		ram_block3a_5.port_b_write_enable_clock = "clock1",
		ram_block3a_5.ram_block_type = "AUTO",
		ram_block3a_5.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block3a_6
	( 
	.clk0(clock0),
	.clk1(clock1),
	.portaaddr({address_a_wire[7:0]}),
	.portadatain({data_a[6]}),
	.portadataout(wire_ram_block3a_6portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdatain({data_b[6]}),
	.portbdataout(wire_ram_block3a_6portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_6.clk0_core_clock_enable = "none",
		ram_block3a_6.clk0_input_clock_enable = "none",
		ram_block3a_6.clk1_core_clock_enable = "none",
		ram_block3a_6.clk1_input_clock_enable = "none",
		ram_block3a_6.connectivity_checking = "OFF",
		ram_block3a_6.init_file = "D.mif",
		ram_block3a_6.init_file_layout = "port_a",
		ram_block3a_6.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_6.mem_init0 = 256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFFFF7FF0000,
		ram_block3a_6.mixed_port_feed_through_mode = "dont_care",
		ram_block3a_6.operation_mode = "bidir_dual_port",
		ram_block3a_6.port_a_address_width = 8,
		ram_block3a_6.port_a_data_out_clear = "none",
		ram_block3a_6.port_a_data_width = 1,
		ram_block3a_6.port_a_first_address = 0,
		ram_block3a_6.port_a_first_bit_number = 6,
		ram_block3a_6.port_a_last_address = 255,
		ram_block3a_6.port_a_logical_ram_depth = 256,
		ram_block3a_6.port_a_logical_ram_width = 16,
		ram_block3a_6.port_a_read_during_write_mode = "old_data",
		ram_block3a_6.port_b_address_clock = "clock1",
		ram_block3a_6.port_b_address_width = 8,
		ram_block3a_6.port_b_data_in_clock = "clock1",
		ram_block3a_6.port_b_data_out_clear = "none",
		ram_block3a_6.port_b_data_width = 1,
		ram_block3a_6.port_b_first_address = 0,
		ram_block3a_6.port_b_first_bit_number = 6,
		ram_block3a_6.port_b_last_address = 255,
		ram_block3a_6.port_b_logical_ram_depth = 256,
		ram_block3a_6.port_b_logical_ram_width = 16,
		ram_block3a_6.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block3a_6.port_b_read_enable_clock = "clock1",
		ram_block3a_6.port_b_write_enable_clock = "clock1",
		ram_block3a_6.ram_block_type = "AUTO",
		ram_block3a_6.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block3a_7
	( 
	.clk0(clock0),
	.clk1(clock1),
	.portaaddr({address_a_wire[7:0]}),
	.portadatain({data_a[7]}),
	.portadataout(wire_ram_block3a_7portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdatain({data_b[7]}),
	.portbdataout(wire_ram_block3a_7portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_7.clk0_core_clock_enable = "none",
		ram_block3a_7.clk0_input_clock_enable = "none",
		ram_block3a_7.clk1_core_clock_enable = "none",
		ram_block3a_7.clk1_input_clock_enable = "none",
		ram_block3a_7.connectivity_checking = "OFF",
		ram_block3a_7.init_file = "D.mif",
		ram_block3a_7.init_file_layout = "port_a",
		ram_block3a_7.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_7.mem_init0 = 256'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFFBFFFFFE0000,
		ram_block3a_7.mixed_port_feed_through_mode = "dont_care",
		ram_block3a_7.operation_mode = "bidir_dual_port",
		ram_block3a_7.port_a_address_width = 8,
		ram_block3a_7.port_a_data_out_clear = "none",
		ram_block3a_7.port_a_data_width = 1,
		ram_block3a_7.port_a_first_address = 0,
		ram_block3a_7.port_a_first_bit_number = 7,
		ram_block3a_7.port_a_last_address = 255,
		ram_block3a_7.port_a_logical_ram_depth = 256,
		ram_block3a_7.port_a_logical_ram_width = 16,
		ram_block3a_7.port_a_read_during_write_mode = "old_data",
		ram_block3a_7.port_b_address_clock = "clock1",
		ram_block3a_7.port_b_address_width = 8,
		ram_block3a_7.port_b_data_in_clock = "clock1",
		ram_block3a_7.port_b_data_out_clear = "none",
		ram_block3a_7.port_b_data_width = 1,
		ram_block3a_7.port_b_first_address = 0,
		ram_block3a_7.port_b_first_bit_number = 7,
		ram_block3a_7.port_b_last_address = 255,
		ram_block3a_7.port_b_logical_ram_depth = 256,
		ram_block3a_7.port_b_logical_ram_width = 16,
		ram_block3a_7.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block3a_7.port_b_read_enable_clock = "clock1",
		ram_block3a_7.port_b_write_enable_clock = "clock1",
		ram_block3a_7.ram_block_type = "AUTO",
		ram_block3a_7.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block3a_8
	( 
	.clk0(clock0),
	.clk1(clock1),
	.portaaddr({address_a_wire[7:0]}),
	.portadatain({data_a[8]}),
	.portadataout(wire_ram_block3a_8portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdatain({data_b[8]}),
	.portbdataout(wire_ram_block3a_8portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_8.clk0_core_clock_enable = "none",
		ram_block3a_8.clk0_input_clock_enable = "none",
		ram_block3a_8.clk1_core_clock_enable = "none",
		ram_block3a_8.clk1_input_clock_enable = "none",
		ram_block3a_8.connectivity_checking = "OFF",
		ram_block3a_8.init_file = "D.mif",
		ram_block3a_8.init_file_layout = "port_a",
		ram_block3a_8.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_8.mem_init0 = 256'h0000000000000000000000000000000040000000000000001000000008000000,
		ram_block3a_8.mixed_port_feed_through_mode = "dont_care",
		ram_block3a_8.operation_mode = "bidir_dual_port",
		ram_block3a_8.port_a_address_width = 8,
		ram_block3a_8.port_a_data_out_clear = "none",
		ram_block3a_8.port_a_data_width = 1,
		ram_block3a_8.port_a_first_address = 0,
		ram_block3a_8.port_a_first_bit_number = 8,
		ram_block3a_8.port_a_last_address = 255,
		ram_block3a_8.port_a_logical_ram_depth = 256,
		ram_block3a_8.port_a_logical_ram_width = 16,
		ram_block3a_8.port_a_read_during_write_mode = "old_data",
		ram_block3a_8.port_b_address_clock = "clock1",
		ram_block3a_8.port_b_address_width = 8,
		ram_block3a_8.port_b_data_in_clock = "clock1",
		ram_block3a_8.port_b_data_out_clear = "none",
		ram_block3a_8.port_b_data_width = 1,
		ram_block3a_8.port_b_first_address = 0,
		ram_block3a_8.port_b_first_bit_number = 8,
		ram_block3a_8.port_b_last_address = 255,
		ram_block3a_8.port_b_logical_ram_depth = 256,
		ram_block3a_8.port_b_logical_ram_width = 16,
		ram_block3a_8.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block3a_8.port_b_read_enable_clock = "clock1",
		ram_block3a_8.port_b_write_enable_clock = "clock1",
		ram_block3a_8.ram_block_type = "AUTO",
		ram_block3a_8.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block3a_9
	( 
	.clk0(clock0),
	.clk1(clock1),
	.portaaddr({address_a_wire[7:0]}),
	.portadatain({data_a[9]}),
	.portadataout(wire_ram_block3a_9portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdatain({data_b[9]}),
	.portbdataout(wire_ram_block3a_9portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_9.clk0_core_clock_enable = "none",
		ram_block3a_9.clk0_input_clock_enable = "none",
		ram_block3a_9.clk1_core_clock_enable = "none",
		ram_block3a_9.clk1_input_clock_enable = "none",
		ram_block3a_9.connectivity_checking = "OFF",
		ram_block3a_9.init_file = "D.mif",
		ram_block3a_9.init_file_layout = "port_a",
		ram_block3a_9.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_9.mem_init0 = 256'h0000000000000000000000000000000000000000000000000000000000000000,
		ram_block3a_9.mixed_port_feed_through_mode = "dont_care",
		ram_block3a_9.operation_mode = "bidir_dual_port",
		ram_block3a_9.port_a_address_width = 8,
		ram_block3a_9.port_a_data_out_clear = "none",
		ram_block3a_9.port_a_data_width = 1,
		ram_block3a_9.port_a_first_address = 0,
		ram_block3a_9.port_a_first_bit_number = 9,
		ram_block3a_9.port_a_last_address = 255,
		ram_block3a_9.port_a_logical_ram_depth = 256,
		ram_block3a_9.port_a_logical_ram_width = 16,
		ram_block3a_9.port_a_read_during_write_mode = "old_data",
		ram_block3a_9.port_b_address_clock = "clock1",
		ram_block3a_9.port_b_address_width = 8,
		ram_block3a_9.port_b_data_in_clock = "clock1",
		ram_block3a_9.port_b_data_out_clear = "none",
		ram_block3a_9.port_b_data_width = 1,
		ram_block3a_9.port_b_first_address = 0,
		ram_block3a_9.port_b_first_bit_number = 9,
		ram_block3a_9.port_b_last_address = 255,
		ram_block3a_9.port_b_logical_ram_depth = 256,
		ram_block3a_9.port_b_logical_ram_width = 16,
		ram_block3a_9.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block3a_9.port_b_read_enable_clock = "clock1",
		ram_block3a_9.port_b_write_enable_clock = "clock1",
		ram_block3a_9.ram_block_type = "AUTO",
		ram_block3a_9.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block3a_10
	( 
	.clk0(clock0),
	.clk1(clock1),
	.portaaddr({address_a_wire[7:0]}),
	.portadatain({data_a[10]}),
	.portadataout(wire_ram_block3a_10portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdatain({data_b[10]}),
	.portbdataout(wire_ram_block3a_10portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_10.clk0_core_clock_enable = "none",
		ram_block3a_10.clk0_input_clock_enable = "none",
		ram_block3a_10.clk1_core_clock_enable = "none",
		ram_block3a_10.clk1_input_clock_enable = "none",
		ram_block3a_10.connectivity_checking = "OFF",
		ram_block3a_10.init_file = "D.mif",
		ram_block3a_10.init_file_layout = "port_a",
		ram_block3a_10.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_10.mem_init0 = 256'h0000000000000000000000000000000000000000000000000000000000000000,
		ram_block3a_10.mixed_port_feed_through_mode = "dont_care",
		ram_block3a_10.operation_mode = "bidir_dual_port",
		ram_block3a_10.port_a_address_width = 8,
		ram_block3a_10.port_a_data_out_clear = "none",
		ram_block3a_10.port_a_data_width = 1,
		ram_block3a_10.port_a_first_address = 0,
		ram_block3a_10.port_a_first_bit_number = 10,
		ram_block3a_10.port_a_last_address = 255,
		ram_block3a_10.port_a_logical_ram_depth = 256,
		ram_block3a_10.port_a_logical_ram_width = 16,
		ram_block3a_10.port_a_read_during_write_mode = "old_data",
		ram_block3a_10.port_b_address_clock = "clock1",
		ram_block3a_10.port_b_address_width = 8,
		ram_block3a_10.port_b_data_in_clock = "clock1",
		ram_block3a_10.port_b_data_out_clear = "none",
		ram_block3a_10.port_b_data_width = 1,
		ram_block3a_10.port_b_first_address = 0,
		ram_block3a_10.port_b_first_bit_number = 10,
		ram_block3a_10.port_b_last_address = 255,
		ram_block3a_10.port_b_logical_ram_depth = 256,
		ram_block3a_10.port_b_logical_ram_width = 16,
		ram_block3a_10.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block3a_10.port_b_read_enable_clock = "clock1",
		ram_block3a_10.port_b_write_enable_clock = "clock1",
		ram_block3a_10.ram_block_type = "AUTO",
		ram_block3a_10.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block3a_11
	( 
	.clk0(clock0),
	.clk1(clock1),
	.portaaddr({address_a_wire[7:0]}),
	.portadatain({data_a[11]}),
	.portadataout(wire_ram_block3a_11portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdatain({data_b[11]}),
	.portbdataout(wire_ram_block3a_11portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_11.clk0_core_clock_enable = "none",
		ram_block3a_11.clk0_input_clock_enable = "none",
		ram_block3a_11.clk1_core_clock_enable = "none",
		ram_block3a_11.clk1_input_clock_enable = "none",
		ram_block3a_11.connectivity_checking = "OFF",
		ram_block3a_11.init_file = "D.mif",
		ram_block3a_11.init_file_layout = "port_a",
		ram_block3a_11.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_11.mem_init0 = 256'h0000000000000000000000000000000000000000000000000000000000000000,
		ram_block3a_11.mixed_port_feed_through_mode = "dont_care",
		ram_block3a_11.operation_mode = "bidir_dual_port",
		ram_block3a_11.port_a_address_width = 8,
		ram_block3a_11.port_a_data_out_clear = "none",
		ram_block3a_11.port_a_data_width = 1,
		ram_block3a_11.port_a_first_address = 0,
		ram_block3a_11.port_a_first_bit_number = 11,
		ram_block3a_11.port_a_last_address = 255,
		ram_block3a_11.port_a_logical_ram_depth = 256,
		ram_block3a_11.port_a_logical_ram_width = 16,
		ram_block3a_11.port_a_read_during_write_mode = "old_data",
		ram_block3a_11.port_b_address_clock = "clock1",
		ram_block3a_11.port_b_address_width = 8,
		ram_block3a_11.port_b_data_in_clock = "clock1",
		ram_block3a_11.port_b_data_out_clear = "none",
		ram_block3a_11.port_b_data_width = 1,
		ram_block3a_11.port_b_first_address = 0,
		ram_block3a_11.port_b_first_bit_number = 11,
		ram_block3a_11.port_b_last_address = 255,
		ram_block3a_11.port_b_logical_ram_depth = 256,
		ram_block3a_11.port_b_logical_ram_width = 16,
		ram_block3a_11.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block3a_11.port_b_read_enable_clock = "clock1",
		ram_block3a_11.port_b_write_enable_clock = "clock1",
		ram_block3a_11.ram_block_type = "AUTO",
		ram_block3a_11.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block3a_12
	( 
	.clk0(clock0),
	.clk1(clock1),
	.portaaddr({address_a_wire[7:0]}),
	.portadatain({data_a[12]}),
	.portadataout(wire_ram_block3a_12portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdatain({data_b[12]}),
	.portbdataout(wire_ram_block3a_12portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_12.clk0_core_clock_enable = "none",
		ram_block3a_12.clk0_input_clock_enable = "none",
		ram_block3a_12.clk1_core_clock_enable = "none",
		ram_block3a_12.clk1_input_clock_enable = "none",
		ram_block3a_12.connectivity_checking = "OFF",
		ram_block3a_12.init_file = "D.mif",
		ram_block3a_12.init_file_layout = "port_a",
		ram_block3a_12.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_12.mem_init0 = 256'h0000000000000000000000000000000040000000000000001000000000000000,
		ram_block3a_12.mixed_port_feed_through_mode = "dont_care",
		ram_block3a_12.operation_mode = "bidir_dual_port",
		ram_block3a_12.port_a_address_width = 8,
		ram_block3a_12.port_a_data_out_clear = "none",
		ram_block3a_12.port_a_data_width = 1,
		ram_block3a_12.port_a_first_address = 0,
		ram_block3a_12.port_a_first_bit_number = 12,
		ram_block3a_12.port_a_last_address = 255,
		ram_block3a_12.port_a_logical_ram_depth = 256,
		ram_block3a_12.port_a_logical_ram_width = 16,
		ram_block3a_12.port_a_read_during_write_mode = "old_data",
		ram_block3a_12.port_b_address_clock = "clock1",
		ram_block3a_12.port_b_address_width = 8,
		ram_block3a_12.port_b_data_in_clock = "clock1",
		ram_block3a_12.port_b_data_out_clear = "none",
		ram_block3a_12.port_b_data_width = 1,
		ram_block3a_12.port_b_first_address = 0,
		ram_block3a_12.port_b_first_bit_number = 12,
		ram_block3a_12.port_b_last_address = 255,
		ram_block3a_12.port_b_logical_ram_depth = 256,
		ram_block3a_12.port_b_logical_ram_width = 16,
		ram_block3a_12.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block3a_12.port_b_read_enable_clock = "clock1",
		ram_block3a_12.port_b_write_enable_clock = "clock1",
		ram_block3a_12.ram_block_type = "AUTO",
		ram_block3a_12.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block3a_13
	( 
	.clk0(clock0),
	.clk1(clock1),
	.portaaddr({address_a_wire[7:0]}),
	.portadatain({data_a[13]}),
	.portadataout(wire_ram_block3a_13portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdatain({data_b[13]}),
	.portbdataout(wire_ram_block3a_13portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_13.clk0_core_clock_enable = "none",
		ram_block3a_13.clk0_input_clock_enable = "none",
		ram_block3a_13.clk1_core_clock_enable = "none",
		ram_block3a_13.clk1_input_clock_enable = "none",
		ram_block3a_13.connectivity_checking = "OFF",
		ram_block3a_13.init_file = "D.mif",
		ram_block3a_13.init_file_layout = "port_a",
		ram_block3a_13.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_13.mem_init0 = 256'h0000000000000000000000000000000040000000000000001000040008000000,
		ram_block3a_13.mixed_port_feed_through_mode = "dont_care",
		ram_block3a_13.operation_mode = "bidir_dual_port",
		ram_block3a_13.port_a_address_width = 8,
		ram_block3a_13.port_a_data_out_clear = "none",
		ram_block3a_13.port_a_data_width = 1,
		ram_block3a_13.port_a_first_address = 0,
		ram_block3a_13.port_a_first_bit_number = 13,
		ram_block3a_13.port_a_last_address = 255,
		ram_block3a_13.port_a_logical_ram_depth = 256,
		ram_block3a_13.port_a_logical_ram_width = 16,
		ram_block3a_13.port_a_read_during_write_mode = "old_data",
		ram_block3a_13.port_b_address_clock = "clock1",
		ram_block3a_13.port_b_address_width = 8,
		ram_block3a_13.port_b_data_in_clock = "clock1",
		ram_block3a_13.port_b_data_out_clear = "none",
		ram_block3a_13.port_b_data_width = 1,
		ram_block3a_13.port_b_first_address = 0,
		ram_block3a_13.port_b_first_bit_number = 13,
		ram_block3a_13.port_b_last_address = 255,
		ram_block3a_13.port_b_logical_ram_depth = 256,
		ram_block3a_13.port_b_logical_ram_width = 16,
		ram_block3a_13.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block3a_13.port_b_read_enable_clock = "clock1",
		ram_block3a_13.port_b_write_enable_clock = "clock1",
		ram_block3a_13.ram_block_type = "AUTO",
		ram_block3a_13.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block3a_14
	( 
	.clk0(clock0),
	.clk1(clock1),
	.portaaddr({address_a_wire[7:0]}),
	.portadatain({data_a[14]}),
	.portadataout(wire_ram_block3a_14portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdatain({data_b[14]}),
	.portbdataout(wire_ram_block3a_14portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_14.clk0_core_clock_enable = "none",
		ram_block3a_14.clk0_input_clock_enable = "none",
		ram_block3a_14.clk1_core_clock_enable = "none",
		ram_block3a_14.clk1_input_clock_enable = "none",
		ram_block3a_14.connectivity_checking = "OFF",
		ram_block3a_14.init_file = "D.mif",
		ram_block3a_14.init_file_layout = "port_a",
		ram_block3a_14.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_14.mem_init0 = 256'h0000000000000000000000000000000000000000000000001000000000000000,
		ram_block3a_14.mixed_port_feed_through_mode = "dont_care",
		ram_block3a_14.operation_mode = "bidir_dual_port",
		ram_block3a_14.port_a_address_width = 8,
		ram_block3a_14.port_a_data_out_clear = "none",
		ram_block3a_14.port_a_data_width = 1,
		ram_block3a_14.port_a_first_address = 0,
		ram_block3a_14.port_a_first_bit_number = 14,
		ram_block3a_14.port_a_last_address = 255,
		ram_block3a_14.port_a_logical_ram_depth = 256,
		ram_block3a_14.port_a_logical_ram_width = 16,
		ram_block3a_14.port_a_read_during_write_mode = "old_data",
		ram_block3a_14.port_b_address_clock = "clock1",
		ram_block3a_14.port_b_address_width = 8,
		ram_block3a_14.port_b_data_in_clock = "clock1",
		ram_block3a_14.port_b_data_out_clear = "none",
		ram_block3a_14.port_b_data_width = 1,
		ram_block3a_14.port_b_first_address = 0,
		ram_block3a_14.port_b_first_bit_number = 14,
		ram_block3a_14.port_b_last_address = 255,
		ram_block3a_14.port_b_logical_ram_depth = 256,
		ram_block3a_14.port_b_logical_ram_width = 16,
		ram_block3a_14.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block3a_14.port_b_read_enable_clock = "clock1",
		ram_block3a_14.port_b_write_enable_clock = "clock1",
		ram_block3a_14.ram_block_type = "AUTO",
		ram_block3a_14.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block3a_15
	( 
	.clk0(clock0),
	.clk1(clock1),
	.portaaddr({address_a_wire[7:0]}),
	.portadatain({data_a[15]}),
	.portadataout(wire_ram_block3a_15portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[7:0]}),
	.portbdatain({data_b[15]}),
	.portbdataout(wire_ram_block3a_15portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block3a_15.clk0_core_clock_enable = "none",
		ram_block3a_15.clk0_input_clock_enable = "none",
		ram_block3a_15.clk1_core_clock_enable = "none",
		ram_block3a_15.clk1_input_clock_enable = "none",
		ram_block3a_15.connectivity_checking = "OFF",
		ram_block3a_15.init_file = "D.mif",
		ram_block3a_15.init_file_layout = "port_a",
		ram_block3a_15.logical_ram_name = "ALTSYNCRAM",
		ram_block3a_15.mem_init0 = 256'h0000000000000000000000000000000040000000000000000000040000000000,
		ram_block3a_15.mixed_port_feed_through_mode = "dont_care",
		ram_block3a_15.operation_mode = "bidir_dual_port",
		ram_block3a_15.port_a_address_width = 8,
		ram_block3a_15.port_a_data_out_clear = "none",
		ram_block3a_15.port_a_data_width = 1,
		ram_block3a_15.port_a_first_address = 0,
		ram_block3a_15.port_a_first_bit_number = 15,
		ram_block3a_15.port_a_last_address = 255,
		ram_block3a_15.port_a_logical_ram_depth = 256,
		ram_block3a_15.port_a_logical_ram_width = 16,
		ram_block3a_15.port_a_read_during_write_mode = "old_data",
		ram_block3a_15.port_b_address_clock = "clock1",
		ram_block3a_15.port_b_address_width = 8,
		ram_block3a_15.port_b_data_in_clock = "clock1",
		ram_block3a_15.port_b_data_out_clear = "none",
		ram_block3a_15.port_b_data_width = 1,
		ram_block3a_15.port_b_first_address = 0,
		ram_block3a_15.port_b_first_bit_number = 15,
		ram_block3a_15.port_b_last_address = 255,
		ram_block3a_15.port_b_logical_ram_depth = 256,
		ram_block3a_15.port_b_logical_ram_width = 16,
		ram_block3a_15.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block3a_15.port_b_read_enable_clock = "clock1",
		ram_block3a_15.port_b_write_enable_clock = "clock1",
		ram_block3a_15.ram_block_type = "AUTO",
		ram_block3a_15.lpm_type = "cycloneive_ram_block";
	assign
		address_a_wire = address_a,
		address_b_wire = address_b,
		q_a = {wire_ram_block3a_15portadataout[0], wire_ram_block3a_14portadataout[0], wire_ram_block3a_13portadataout[0], wire_ram_block3a_12portadataout[0], wire_ram_block3a_11portadataout[0], wire_ram_block3a_10portadataout[0], wire_ram_block3a_9portadataout[0], wire_ram_block3a_8portadataout[0], wire_ram_block3a_7portadataout[0], wire_ram_block3a_6portadataout[0], wire_ram_block3a_5portadataout[0], wire_ram_block3a_4portadataout[0], wire_ram_block3a_3portadataout[0], wire_ram_block3a_2portadataout[0], wire_ram_block3a_1portadataout[0], wire_ram_block3a_0portadataout[0]},
		q_b = {wire_ram_block3a_15portbdataout[0], wire_ram_block3a_14portbdataout[0], wire_ram_block3a_13portbdataout[0], wire_ram_block3a_12portbdataout[0], wire_ram_block3a_11portbdataout[0], wire_ram_block3a_10portbdataout[0], wire_ram_block3a_9portbdataout[0], wire_ram_block3a_8portbdataout[0], wire_ram_block3a_7portbdataout[0], wire_ram_block3a_6portbdataout[0], wire_ram_block3a_5portbdataout[0], wire_ram_block3a_4portbdataout[0], wire_ram_block3a_3portbdataout[0], wire_ram_block3a_2portbdataout[0], wire_ram_block3a_1portbdataout[0], wire_ram_block3a_0portbdataout[0]};
endmodule //DataMemory_altsyncram1

//synthesis_resources = M9K 1 sld_mod_ram_rom 1 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  DataMemory_altsyncram
	( 
	address_a,
	clock0,
	data_a,
	q_a,
	wren_a) /* synthesis synthesis_clearbox=1 */;
	input   [7:0]  address_a;
	input   clock0;
	input   [15:0]  data_a;
	output   [15:0]  q_a;
	input   wren_a;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1   clock0;
	tri1   [15:0]  data_a;
	tri0   wren_a;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [15:0]   wire_altsyncram1_q_a;
	wire  [15:0]   wire_altsyncram1_q_b;
	wire  [7:0]   wire_mgl_prim2_address;
	wire  [15:0]   wire_mgl_prim2_data_write;
	wire  wire_mgl_prim2_enable_write;
	wire  wire_mgl_prim2_tck_usr;

	DataMemory_altsyncram1   altsyncram1
	( 
	.address_a(address_a),
	.address_b(wire_mgl_prim2_address),
	.clock0(clock0),
	.clock1(wire_mgl_prim2_tck_usr),
	.data_a(data_a),
	.data_b(wire_mgl_prim2_data_write),
	.q_a(wire_altsyncram1_q_a),
	.q_b(wire_altsyncram1_q_b),
	.wren_a(wren_a),
	.wren_b(wire_mgl_prim2_enable_write));
	sld_mod_ram_rom   mgl_prim2
	( 
	.address(wire_mgl_prim2_address),
	.data_read(wire_altsyncram1_q_b),
	.data_write(wire_mgl_prim2_data_write),
	.enable_write(wire_mgl_prim2_enable_write),
	.tck_usr(wire_mgl_prim2_tck_usr));
	defparam
		mgl_prim2.cvalue = 16'b0000000000000000,
		mgl_prim2.is_data_in_ram = 1,
		mgl_prim2.is_readable = 1,
		mgl_prim2.node_name = 1145132097,
		mgl_prim2.numwords = 256,
		mgl_prim2.shift_count_bits = 5,
		mgl_prim2.width_word = 16,
		mgl_prim2.widthad = 8;
	assign
		q_a = wire_altsyncram1_q_a;
endmodule //DataMemory_altsyncram
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module DataMemory (
	address,
	clock,
	data,
	wren,
	q)/* synthesis synthesis_clearbox = 1 */;

	input	[7:0]  address;
	input	  clock;
	input	[15:0]  data;
	input	  wren;
	output	[15:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1	  clock;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire [15:0] sub_wire0;
	wire [15:0] q = sub_wire0[15:0];

	DataMemory_altsyncram	DataMemory_altsyncram_component (
				.address_a (address),
				.clock0 (clock),
				.data_a (data),
				.wren_a (wren),
				.q_a (sub_wire0));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: ADDRESSSTALL_A NUMERIC "0"
// Retrieval info: PRIVATE: AclrAddr NUMERIC "0"
// Retrieval info: PRIVATE: AclrByte NUMERIC "0"
// Retrieval info: PRIVATE: AclrData NUMERIC "0"
// Retrieval info: PRIVATE: AclrOutput NUMERIC "0"
// Retrieval info: PRIVATE: BYTE_ENABLE NUMERIC "0"
// Retrieval info: PRIVATE: BYTE_SIZE NUMERIC "8"
// Retrieval info: PRIVATE: BlankMemory NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_INPUT_A NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_OUTPUT_A NUMERIC "0"
// Retrieval info: PRIVATE: Clken NUMERIC "0"
// Retrieval info: PRIVATE: DataBusSeparated NUMERIC "1"
// Retrieval info: PRIVATE: IMPLEMENT_IN_LES NUMERIC "0"
// Retrieval info: PRIVATE: INIT_FILE_LAYOUT STRING "PORT_A"
// Retrieval info: PRIVATE: INIT_TO_SIM_X NUMERIC "0"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone IV E"
// Retrieval info: PRIVATE: JTAG_ENABLED NUMERIC "1"
// Retrieval info: PRIVATE: JTAG_ID STRING "DATA"
// Retrieval info: PRIVATE: MAXIMUM_DEPTH NUMERIC "0"
// Retrieval info: PRIVATE: MIFfilename STRING "D.mif"
// Retrieval info: PRIVATE: NUMWORDS_A NUMERIC "256"
// Retrieval info: PRIVATE: RAM_BLOCK_TYPE NUMERIC "0"
// Retrieval info: PRIVATE: READ_DURING_WRITE_MODE_PORT_A NUMERIC "1"
// Retrieval info: PRIVATE: RegAddr NUMERIC "1"
// Retrieval info: PRIVATE: RegData NUMERIC "1"
// Retrieval info: PRIVATE: RegOutput NUMERIC "0"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: PRIVATE: SingleClock NUMERIC "1"
// Retrieval info: PRIVATE: UseDQRAM NUMERIC "1"
// Retrieval info: PRIVATE: WRCONTROL_ACLR_A NUMERIC "0"
// Retrieval info: PRIVATE: WidthAddr NUMERIC "8"
// Retrieval info: PRIVATE: WidthData NUMERIC "16"
// Retrieval info: PRIVATE: rden NUMERIC "0"
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: CONSTANT: CLOCK_ENABLE_INPUT_A STRING "BYPASS"
// Retrieval info: CONSTANT: CLOCK_ENABLE_OUTPUT_A STRING "BYPASS"
// Retrieval info: CONSTANT: INIT_FILE STRING "D.mif"
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Cyclone IV E"
// Retrieval info: CONSTANT: LPM_HINT STRING "ENABLE_RUNTIME_MOD=YES,INSTANCE_NAME=DATA"
// Retrieval info: CONSTANT: LPM_TYPE STRING "altsyncram"
// Retrieval info: CONSTANT: NUMWORDS_A NUMERIC "256"
// Retrieval info: CONSTANT: OPERATION_MODE STRING "SINGLE_PORT"
// Retrieval info: CONSTANT: OUTDATA_ACLR_A STRING "NONE"
// Retrieval info: CONSTANT: OUTDATA_REG_A STRING "UNREGISTERED"
// Retrieval info: CONSTANT: POWER_UP_UNINITIALIZED STRING "FALSE"
// Retrieval info: CONSTANT: READ_DURING_WRITE_MODE_PORT_A STRING "OLD_DATA"
// Retrieval info: CONSTANT: WIDTHAD_A NUMERIC "8"
// Retrieval info: CONSTANT: WIDTH_A NUMERIC "16"
// Retrieval info: CONSTANT: WIDTH_BYTEENA_A NUMERIC "1"
// Retrieval info: USED_PORT: address 0 0 8 0 INPUT NODEFVAL "address[7..0]"
// Retrieval info: USED_PORT: clock 0 0 0 0 INPUT VCC "clock"
// Retrieval info: USED_PORT: data 0 0 16 0 INPUT NODEFVAL "data[15..0]"
// Retrieval info: USED_PORT: q 0 0 16 0 OUTPUT NODEFVAL "q[15..0]"
// Retrieval info: USED_PORT: wren 0 0 0 0 INPUT NODEFVAL "wren"
// Retrieval info: CONNECT: @address_a 0 0 8 0 address 0 0 8 0
// Retrieval info: CONNECT: @clock0 0 0 0 0 clock 0 0 0 0
// Retrieval info: CONNECT: @data_a 0 0 16 0 data 0 0 16 0
// Retrieval info: CONNECT: @wren_a 0 0 0 0 wren 0 0 0 0
// Retrieval info: CONNECT: q 0 0 16 0 @q_a 0 0 16 0
// Retrieval info: GEN_FILE: TYPE_NORMAL DataMemory.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL DataMemory.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL DataMemory.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL DataMemory.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL DataMemory_inst.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL DataMemory_bb.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL DataMemory_syn.v TRUE
// Retrieval info: LIB_FILE: altera_mf
